apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  DB_DSN: 'postgres://dev:dev@host.minikube.internal:5432/dev?sslmode=disable'
  REDIS_HOST: redis:6379
  REDIS_PASS: macaco
  ADDR: :80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: go-app
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: go
spec:
  selector:
    app: go
  ports:
  - name: http
    port: 80
    targetPort: 80